apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
        - name: drush-cache-rebuild
          image: docker.io/umairgl123/drupalportal:v1 
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - |
              php /var/www/html/vendor/bin/drush.php cr
          env:
            - name: MYSQL_DATABASE
              value: "gosi_drupal"
            - name: MYSQL_HOST
              value: "gosi-mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_USER
              value: "gosi_user"
            - name: MYSQL_PASSWORD
              value: "gosi_pass123"
            - name: MYSQL_PORT
              value: "3306"
          volumeMounts:
            - name: vendor-volume
              mountPath: /var/www/html/vendor
              readOnly: false
            - name: composer-json-volume
              mountPath: /var/www/html/composer.json
              readOnly: false
            - name: composer-lock-volume
              mountPath: /var/www/html/composer.lock
              readOnly: false

      containers:
        - name: app
          image: docker.io/umairgl123/drupalportal:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE
              value: "gosi_drupal"
            - name: MYSQL_HOST
              value: "gosi-mysql"
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_USER
              value: "gosi_user"
            - name: MYSQL_PASSWORD
              value: "gosi_pass123"
            - name: MYSQL_PORT
              value: "3306"
          volumeMounts:
            - name: vendor-volume
              mountPath: /var/www/html/vendor
              readOnly: false
            - name: composer-json-volume
              mountPath: /var/www/html/composer.json
              readOnly: false
            - name: composer-lock-volume
              mountPath: /var/www/html/composer.lock
              readOnly: false

      volumes:
        - name: vendor-volume
          hostPath:
            path: /mnt/vendor
            type: Directory

        - name: composer-json-volume
          hostPath:
            path: /mnt/composer.json
            type: File

        - name: composer-lock-volume
          hostPath:
            path: /mnt/composer.lock
            type: File

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # Change this port if needed
  selector:
    app: my-app


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75